Guard release mismatch on debian/ubuntu (#37)
install-rhel-* fetch from /etc/system-release-cpe, so release mismatch
will not happen.

---------

Signed-off-by: Kentaro Hayashi <hayashi@clear-code.com>

diff --git a/make-install-script.erb b/make-install-script.erb
--- a/make-install-script.erb
+++ b/make-install-script.erb
@@ -171,6 +171,14 @@ echo "You will be prompted for your password by sudo."
 sudo -k
 
 # run inside sudo
+executed_distribution=$(cat /etc/os-release | grep "^ID=" | cut -d'=' -f2)
+executed_release=$(cat /etc/os-release | grep VERSION_CODENAME | cut -d'=' -f2)
+if [ ! "${executed_release}" = "<%= install_info[:version] %>" ]; then
+  echo
+  echo "[ERROR] Executed wrong installation script for <%= install_info[:distribution] %> <%= install_info[:version] %> on ${executed_distribution} ${executed_release}"
+  echo
+  exit 1
+fi
 sudo sh <<SCRIPT
 <% if install_info[:channel_version] >= 5 %>
   # use apt-source package which contains keyring
@@ -223,14 +231,17 @@ if [ $? -eq 0 ]; then
   echo ""
   echo "Installation completed. Happy Logging!"
   echo ""
+  exit 0
 else
   echo ""
   echo "Installation incompleted. Check above messages."
   echo ""
+  exit 1
 fi
 <% else %>
 echo ""
 echo "Installation completed. Happy Logging!"
 echo ""
+exit 0
 <% end %>
 <% end %>
